name: Run Copyright and license check from PR

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate patch file
      run: |
        git diff > patch_file.patch

    - name: Print patch file content
      run: |
        cat patch_file.patch
      shell: bash

    - name: Run Python Script Action
      uses: targoy-qti/copyright-license-checker-action@main
      with:
        patch_file: patch_file.patch
